name: Week3 CI Demo

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v3

 

      - name: Run echo command

        if: github.ref == 'refs/heads/main'

        run: echo "CI pipeline is running via GitHub Actions!"
